# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /files/00-DBAI/home/mroebke/Ba/GPUSAT191128/GPUSAT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /files/00-DBAI/home/mroebke/Ba/GPUSAT191128/GPUSAT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /files/00-DBAI/home/mroebke/Ba/GPUSAT191128/GPUSAT/CMakeFiles /files/00-DBAI/home/mroebke/Ba/GPUSAT191128/GPUSAT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /files/00-DBAI/home/mroebke/Ba/GPUSAT191128/GPUSAT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpusat

# Build rule for target.
gpusat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpusat
.PHONY : gpusat

# fast build rule for target.
gpusat/fast:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/build
.PHONY : gpusat/fast

src/FitnessFunctions/CutSetWidthFitnessFunction.o: src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.o

.PHONY : src/FitnessFunctions/CutSetWidthFitnessFunction.o

# target to build an object file
src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.o
.PHONY : src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.o

src/FitnessFunctions/CutSetWidthFitnessFunction.i: src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.i

.PHONY : src/FitnessFunctions/CutSetWidthFitnessFunction.i

# target to preprocess a source file
src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.i
.PHONY : src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.i

src/FitnessFunctions/CutSetWidthFitnessFunction.s: src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.s

.PHONY : src/FitnessFunctions/CutSetWidthFitnessFunction.s

# target to generate assembly for a file
src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.s
.PHONY : src/FitnessFunctions/CutSetWidthFitnessFunction.cpp.s

src/FitnessFunctions/JoinSizeFitnessFunction.o: src/FitnessFunctions/JoinSizeFitnessFunction.cpp.o

.PHONY : src/FitnessFunctions/JoinSizeFitnessFunction.o

# target to build an object file
src/FitnessFunctions/JoinSizeFitnessFunction.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/JoinSizeFitnessFunction.cpp.o
.PHONY : src/FitnessFunctions/JoinSizeFitnessFunction.cpp.o

src/FitnessFunctions/JoinSizeFitnessFunction.i: src/FitnessFunctions/JoinSizeFitnessFunction.cpp.i

.PHONY : src/FitnessFunctions/JoinSizeFitnessFunction.i

# target to preprocess a source file
src/FitnessFunctions/JoinSizeFitnessFunction.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/JoinSizeFitnessFunction.cpp.i
.PHONY : src/FitnessFunctions/JoinSizeFitnessFunction.cpp.i

src/FitnessFunctions/JoinSizeFitnessFunction.s: src/FitnessFunctions/JoinSizeFitnessFunction.cpp.s

.PHONY : src/FitnessFunctions/JoinSizeFitnessFunction.s

# target to generate assembly for a file
src/FitnessFunctions/JoinSizeFitnessFunction.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/JoinSizeFitnessFunction.cpp.s
.PHONY : src/FitnessFunctions/JoinSizeFitnessFunction.cpp.s

src/FitnessFunctions/NumJoinFitnessFunction.o: src/FitnessFunctions/NumJoinFitnessFunction.cpp.o

.PHONY : src/FitnessFunctions/NumJoinFitnessFunction.o

# target to build an object file
src/FitnessFunctions/NumJoinFitnessFunction.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/NumJoinFitnessFunction.cpp.o
.PHONY : src/FitnessFunctions/NumJoinFitnessFunction.cpp.o

src/FitnessFunctions/NumJoinFitnessFunction.i: src/FitnessFunctions/NumJoinFitnessFunction.cpp.i

.PHONY : src/FitnessFunctions/NumJoinFitnessFunction.i

# target to preprocess a source file
src/FitnessFunctions/NumJoinFitnessFunction.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/NumJoinFitnessFunction.cpp.i
.PHONY : src/FitnessFunctions/NumJoinFitnessFunction.cpp.i

src/FitnessFunctions/NumJoinFitnessFunction.s: src/FitnessFunctions/NumJoinFitnessFunction.cpp.s

.PHONY : src/FitnessFunctions/NumJoinFitnessFunction.s

# target to generate assembly for a file
src/FitnessFunctions/NumJoinFitnessFunction.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/NumJoinFitnessFunction.cpp.s
.PHONY : src/FitnessFunctions/NumJoinFitnessFunction.cpp.s

src/FitnessFunctions/WidthCutSetFitnessFunction.o: src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.o

.PHONY : src/FitnessFunctions/WidthCutSetFitnessFunction.o

# target to build an object file
src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.o
.PHONY : src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.o

src/FitnessFunctions/WidthCutSetFitnessFunction.i: src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.i

.PHONY : src/FitnessFunctions/WidthCutSetFitnessFunction.i

# target to preprocess a source file
src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.i
.PHONY : src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.i

src/FitnessFunctions/WidthCutSetFitnessFunction.s: src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.s

.PHONY : src/FitnessFunctions/WidthCutSetFitnessFunction.s

# target to generate assembly for a file
src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.s
.PHONY : src/FitnessFunctions/WidthCutSetFitnessFunction.cpp.s

src/decomposer.o: src/decomposer.cpp.o

.PHONY : src/decomposer.o

# target to build an object file
src/decomposer.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/decomposer.cpp.o
.PHONY : src/decomposer.cpp.o

src/decomposer.i: src/decomposer.cpp.i

.PHONY : src/decomposer.i

# target to preprocess a source file
src/decomposer.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/decomposer.cpp.i
.PHONY : src/decomposer.cpp.i

src/decomposer.s: src/decomposer.cpp.s

.PHONY : src/decomposer.s

# target to generate assembly for a file
src/decomposer.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/decomposer.cpp.s
.PHONY : src/decomposer.cpp.s

src/gpusatparser.o: src/gpusatparser.cpp.o

.PHONY : src/gpusatparser.o

# target to build an object file
src/gpusatparser.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/gpusatparser.cpp.o
.PHONY : src/gpusatparser.cpp.o

src/gpusatparser.i: src/gpusatparser.cpp.i

.PHONY : src/gpusatparser.i

# target to preprocess a source file
src/gpusatparser.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/gpusatparser.cpp.i
.PHONY : src/gpusatparser.cpp.i

src/gpusatparser.s: src/gpusatparser.cpp.s

.PHONY : src/gpusatparser.s

# target to generate assembly for a file
src/gpusatparser.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/gpusatparser.cpp.s
.PHONY : src/gpusatparser.cpp.s

src/gpusatpreprocessor.o: src/gpusatpreprocessor.cpp.o

.PHONY : src/gpusatpreprocessor.o

# target to build an object file
src/gpusatpreprocessor.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/gpusatpreprocessor.cpp.o
.PHONY : src/gpusatpreprocessor.cpp.o

src/gpusatpreprocessor.i: src/gpusatpreprocessor.cpp.i

.PHONY : src/gpusatpreprocessor.i

# target to preprocess a source file
src/gpusatpreprocessor.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/gpusatpreprocessor.cpp.i
.PHONY : src/gpusatpreprocessor.cpp.i

src/gpusatpreprocessor.s: src/gpusatpreprocessor.cpp.s

.PHONY : src/gpusatpreprocessor.s

# target to generate assembly for a file
src/gpusatpreprocessor.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/gpusatpreprocessor.cpp.s
.PHONY : src/gpusatpreprocessor.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/solver.o: src/solver.cpp.o

.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i

.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s

.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) -f CMakeFiles/gpusat.dir/build.make CMakeFiles/gpusat.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... gpusat"
	@echo "... edit_cache"
	@echo "... src/FitnessFunctions/CutSetWidthFitnessFunction.o"
	@echo "... src/FitnessFunctions/CutSetWidthFitnessFunction.i"
	@echo "... src/FitnessFunctions/CutSetWidthFitnessFunction.s"
	@echo "... src/FitnessFunctions/JoinSizeFitnessFunction.o"
	@echo "... src/FitnessFunctions/JoinSizeFitnessFunction.i"
	@echo "... src/FitnessFunctions/JoinSizeFitnessFunction.s"
	@echo "... src/FitnessFunctions/NumJoinFitnessFunction.o"
	@echo "... src/FitnessFunctions/NumJoinFitnessFunction.i"
	@echo "... src/FitnessFunctions/NumJoinFitnessFunction.s"
	@echo "... src/FitnessFunctions/WidthCutSetFitnessFunction.o"
	@echo "... src/FitnessFunctions/WidthCutSetFitnessFunction.i"
	@echo "... src/FitnessFunctions/WidthCutSetFitnessFunction.s"
	@echo "... src/decomposer.o"
	@echo "... src/decomposer.i"
	@echo "... src/decomposer.s"
	@echo "... src/gpusatparser.o"
	@echo "... src/gpusatparser.i"
	@echo "... src/gpusatparser.s"
	@echo "... src/gpusatpreprocessor.o"
	@echo "... src/gpusatpreprocessor.i"
	@echo "... src/gpusatpreprocessor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

