GPUSAT: gpusat::Preprocessor Class Reference
gpusat::Preprocessor Class Reference
#include <gpusatpreprocessor.h>
Static Public Member Functions
static void preprocessDecomp (bagType *decomp, cl_long combineWidth)
static void preprocessFacts (treedecType &decomp, satformulaType &formula, cl_double &defaultWeight)
Member Function Documentation
preprocessDecomp()
void gpusat::Preprocessor::preprocessDecomp (bagType * decomp, cl_long combineWidth) static
preprocess the tree decomposition
Parameters
decomp the tree decomposition
combineWidth max width to combine bags
References gpusat::compTreedType(), gpusat::bagType::edges, and gpusat::bagType::variables.
Referenced by main().
preprocessFacts()
void gpusat::Preprocessor::preprocessFacts (treedecType & decomp, satformulaType & formula, cl_double & defaultWeight) static
removes facts from the sat formula
Parameters
decomp the tree decomposition
formula the sat formula
defaultWeight for WMC the product of the weights of the removed literals
References gpusat::treedecType::bags, gpusat::satformulaType::clauses, gpusat::compVars(), gpusat::satformulaType::facts, gpusat::treedecType::numVars, gpusat::satformulaType::numVars, gpusat::satformulaType::numWeights, gpusat::satformulaType::unsat, and gpusat::satformulaType::variableWeights.
Referenced by main().
The documentation for this class was generated from the following files:
include/gpusatpreprocessor.h
src/gpusatpreprocessor.cpp