GPUSAT: gpusat::BagMatrix Class Reference
gpusat::BagMatrix Class Reference
#include <visualization.h>
Public Member Functions
BagMatrix ()
BagMatrix (size_t rows, size_t cols)
size_t columns ()
cl_long & operator() (size_t i, size_t j)
cl_long operator() (size_t i, size_t j) const
size_t rows ()
Detailed Description
Class for storing 2dim 'ulong' values using vector and a 1dim memory layout. See https://stackoverflow.com/a/2076668 Example usage:
BagMatrix mygrid (5, 5); for (int r = 0; r < mygrid.rows(); r++){ for (int c = 0; c < mygrid.columns(); c++){ mygrid[r][c] = r * c; } } Print the array for (int r = 0; r < mygrid.rows(); r++){ std::cout << std::hex << &(mygrid[r][0]) << std::dec; std::cout << ": "; for (int c = 0; c < mygrid.columns(); c++){ std::cout << mygrid[r][c] << ' '; } std::cout << std::endl; }
Constructor & Destructor Documentation
BagMatrix() [1/2]
gpusat::BagMatrix::BagMatrix (size_t rows, size_t cols)
BagMatrix() [2/2]
gpusat::BagMatrix::BagMatrix ()
Member Function Documentation
columns()
size_t gpusat::BagMatrix::columns () inline
Referenced by gpusat::solJson(), and gpusat::Visualization::tdTimelineAppend().
operator()() [1/2]
cl_long & gpusat::BagMatrix::operator() (size_t i, size_t j)
operator()() [2/2]
cl_long gpusat::BagMatrix::operator() (size_t i, size_t j) const
rows()
size_t gpusat::BagMatrix::rows () inline
Referenced by gpusat::Visualization::tdTimelineAppend().
The documentation for this class was generated from the following files:
include/visualization.h
src/visualization.cpp