GPUSAT: gpusat::Visualization Class Reference
gpusat::Visualization Class Reference
#include <visualization.h>
Public Member Functions
Visualization (std::string filename)
Json::Value getClausesJson ()
std::string getFilename ()
Json::Value getTdTimeline ()
Json::Value getTreeDecJson ()
Json::StreamWriterBuilder * getWriterBuilder ()
bool isEnabled ()
void tdTimelineAppend (std::vector< cl_long > bag_ids)
void tdTimelineAppend (std::vector< cl_long > bag_ids, TableLines tablelines, std::string const toplabel="", std::string const bottomlabel="", bool transpose=true)
void testJson ()
void visuClauses (satformulaType *sat)
void visuTreeDec (treedecType *treeDec)
void writeJsonFile (bool append=false)
void writeJsonToStdout (Json::StreamWriter::Factory const &factory, Json::Value const &value, Json::OStream *sout=&std::cout)
void writeJsonToStdout (Json::Value const &value, Json::OStream *sout=&std::cout)
Constructor & Destructor Documentation
Visualization()
gpusat::Visualization::Visualization (std::string filename) inline
References isEnabled().
Member Function Documentation
getClausesJson()
Json::Value gpusat::Visualization::getClausesJson () inline
getFilename()
std::string gpusat::Visualization::getFilename () inline
getTdTimeline()
Json::Value gpusat::Visualization::getTdTimeline () inline
getTreeDecJson()
Json::Value gpusat::Visualization::getTreeDecJson () inline
getWriterBuilder()
Json::StreamWriterBuilder * gpusat::Visualization::getWriterBuilder ()
Referenced by testJson().
isEnabled()
bool gpusat::Visualization::isEnabled () inline
Referenced by Visualization(), and writeJsonFile().
tdTimelineAppend() [1/2]
void gpusat::Visualization::tdTimelineAppend (std::vector< cl_long > bag_ids)
Only append those bags as one array. Might even be only one bag. The behaviour with zero length is not implemented (yet).
References LOGGER2.
tdTimelineAppend() [2/2]
void gpusat::Visualization::tdTimelineAppend (std::vector< cl_long > bag_ids, TableLines tablelines, std::string const toplabel = "", std::string const bottomlabel = "", bool transpose = true)
bag_ids: asserts not empty
if one: one (IF) solution found
more: join solution found tablelines: all lines for the table toplabel: string to label the whole solution bottomlabel: string to summarize the solution transpose: whether the tablelines are rowfirst (true) or not.
References gpusat::BagMatrix::columns(), gpusat::TableLines::headline, LOGGER2, gpusat::BagMatrix::rows(), gpusat::TableLines::solutions, and gpusat::TableLines::totalSol.
Referenced by gpusat::Solver::solveProblem().
testJson()
void gpusat::Visualization::testJson ()
References getWriterBuilder(), and writeJsonToStdout().
visuClauses()
void gpusat::Visualization::visuClauses (satformulaType * sat)
Save the clauses into the Visualization::clausesJson. Form: List[Dict{INT: List[Int]}] Error if: sat formula is null or empty.
References gpusat::satformulaType::clauses.
Referenced by main().
visuTreeDec()
void gpusat::Visualization::visuTreeDec (treedecType * treeDec)
References gpusat::treedecType::bags, gpusat::bagType::edges, gpusat::bagType::id, and gpusat::treedecType::numVars.
Referenced by main().
writeJsonFile()
void gpusat::Visualization::writeJsonFile (bool append = false)
References isEnabled(), LOGGER, and writeJsonToStdout().
Referenced by main().
writeJsonToStdout() [1/2]
void gpusat::Visualization::writeJsonToStdout (Json::StreamWriter::Factory const & factory, Json::Value const & value, Json::OStream * sout = &std::cout)
Referenced by testJson(), writeJsonFile(), and writeJsonToStdout().
writeJsonToStdout() [2/2]
void gpusat::Visualization::writeJsonToStdout (Json::Value const & value, Json::OStream * sout = &std::cout)
References writeJsonToStdout().
The documentation for this class was generated from the following files:
include/visualization.h
src/visualization.cpp