GPUSAT: gpusat::Graphoutput Class Reference
gpusat::Graphoutput Class Reference
#include <graphoutput.h>
Public Member Functions
Graphoutput (std::string filename)
std::string getFilename ()
void graphEdgeSet (treedecType *dec)
Addes the edges from the tree-decomposition into the graph.
void graphEnd ()
void graphStart (treedecType *dec)
bool isEnabled ()
void neo4jSat (satformulaType *satFormula)
Output Cypherquery to create the nodes from the SAT formula
void neo4jTD (treedecType *treeDec)
void nodeBag (unsigned int id, std::string solution)
Create one node with the corresponding solution in a connected extra bag.
void nodeJoin (unsigned int id1, unsigned int id2, std::string solution)
Creates a node with the solution that joins two bags. Two edges are added to connect the solution.
Static Public Attributes
static const int baseIdJoin = 4 * baseIdSol
static const int baseIdSol = 1'000'000
static const std::string connectbag = "USES_BAG"
static const std::string dualedge = "SHARE_VAR"
static const std::string inbag = "CONTAINS"
static const std::string incidenceedge = "VAR_IN_CLAUSE"
static const std::string primaledge = "SHARE_CLAUSE"
Constructor & Destructor Documentation
Graphoutput()
gpusat::Graphoutput::Graphoutput (std::string filename) inline
Member Function Documentation
getFilename()
std::string gpusat::Graphoutput::getFilename () inline
graphEdgeSet()
void gpusat::Graphoutput::graphEdgeSet (treedecType * dec)
Addes the edges from the tree-decomposition into the graph.
Any outgoing edges from id '0' are not added.
Parameters
dec Pointer to the tree-decomposition containing used edges.
References gpusat::treedecType::bags, and isEnabled().
Referenced by gpusat::Solver::solveProblem().
graphEnd()
void gpusat::Graphoutput::graphEnd ()
References isEnabled().
Referenced by main().
graphStart()
void gpusat::Graphoutput::graphStart (treedecType * dec)
References gpusat::treedecType::bags, and isEnabled().
Referenced by main().
isEnabled()
bool gpusat::Graphoutput::isEnabled () inline
Referenced by graphEdgeSet(), graphEnd(), graphStart(), neo4jSat(), neo4jTD(), nodeBag(), nodeJoin(), and gpusat::Solver::solveProblem().
neo4jSat()
void gpusat::Graphoutput::neo4jSat (satformulaType * satFormula)
Output Cypherquery to create the nodes from the SAT formula
Parameters
satFormula The sat formula.
References gpusat::satformulaType::clauses, dualedge, gpusat::satformulaType::facts, incidenceedge, isEnabled(), gpusat::satformulaType::numVars, primaledge, and gpusat::satformulaType::unsat.
Referenced by main().
neo4jTD()
void gpusat::Graphoutput::neo4jTD (treedecType * treeDec)
References gpusat::treedecType::bags, connectbag, inbag, isEnabled(), gpusat::treedecType::numb, gpusat::treedecType::numVars, and gpusat::treedecType::width.
Referenced by main().
nodeBag()
void gpusat::Graphoutput::nodeBag (unsigned int id, std::string solution)
Create one node with the corresponding solution in a connected extra bag.
Parameters
id The identifier of the bag.
solution The solution in string form.
References isEnabled().
Referenced by gpusat::Solver::solveProblem().
nodeJoin()
void gpusat::Graphoutput::nodeJoin (unsigned int id1, unsigned int id2, std::string solution)
Creates a node with the solution that joins two bags. Two edges are added to connect the solution.
Parameters
id1 The id1.
id2 The id2.
solution The solution.
TODO Edit XML Comment Template for nodeJoin
References isEnabled().
Referenced by gpusat::Solver::solveProblem().
Member Data Documentation
baseIdJoin
const int gpusat::Graphoutput::baseIdJoin = 4 * baseIdSol static
baseIdSol
const int gpusat::Graphoutput::baseIdSol = 1'000'000 static
connectbag
const std::string gpusat::Graphoutput::connectbag = "USES_BAG" static
Referenced by neo4jTD().
dualedge
const std::string gpusat::Graphoutput::dualedge = "SHARE_VAR" static
Referenced by neo4jSat().
inbag
const std::string gpusat::Graphoutput::inbag = "CONTAINS" static
Referenced by neo4jTD().
incidenceedge
const std::string gpusat::Graphoutput::incidenceedge = "VAR_IN_CLAUSE" static
Referenced by neo4jSat().
primaledge
const std::string gpusat::Graphoutput::primaledge = "SHARE_CLAUSE" static
Referenced by neo4jSat().
The documentation for this class was generated from the following files:
include/graphoutput.h
src/graphoutput.cpp