GPUSAT: gpusat::Solver Class Reference
gpusat::Solver Class Reference
#include <solver.h>
Public Member Functions
Solver (cl::Context &context_, cl::CommandQueue &queue_, cl::Program &program_, cl_long memorySize_, cl_long maxMemoryBuffer_, dataStructure solutionType_, cl_long maxBag_, bool verbose_, Graphoutput *graphoutput_, Visualization *visualization_)
void solveProblem (treedecType &decomp, satformulaType &formula, bagType &node, bagType &pnode, nodeType lastNode)
Solves the sat formula with a given decomposition.
Public Attributes
Graphoutput * graphoutput
cl_long isSat = 1
cl_long maxBag = 0
cl_long maxMemoryBuffer = 0
cl_long maxTableSize = 0
cl_long numIntroduceForget = 0
cl_long numJoin = 0
dataStructure solutionType = dataStructure::TREE
bool verbose = false
Visualization * visualization
Protected Member Functions
void cleanTree (treeType &table, cl_long size, cl_long numVars, bagType &node, cl_long nextSize)
void combineTree (treeType &to, treeType &from, cl_long numVars)
void solveIntroduceForget (satformulaType &formula, bagType &pnode, bagType &node, bagType &cnode, bool leaf, nodeType nextNode)
void solveJoin (bagType &node, bagType &edge1, bagType &edge2, satformulaType &formula, nodeType nextNode)
Protected Attributes
cl::Context & context
cl_long memorySize
cl::Program & program
cl::CommandQueue & queue
Detailed Description
Organizes the process of solving a sat problem in the given context.
Constructor & Destructor Documentation
Solver()
gpusat::Solver::Solver (cl::Context & context_, cl::CommandQueue & queue_, cl::Program & program_, cl_long memorySize_, cl_long maxMemoryBuffer_, dataStructure solutionType_, cl_long maxBag_, bool verbose_, Graphoutput * graphoutput_, Visualization * visualization_) inline
Parameters
context_ the given context as hardware
queue_
program_
memorySize_
maxMemoryBuffer_
solutionType_
maxBag_
verbose_
graphoutput_
visualization_
Member Function Documentation
cleanTree()
void gpusat::Solver::cleanTree (treeType & table, cl_long size, cl_long numVars, bagType & node, cl_long nextSize) protected
Parameters
table
size
numVars
node
References context, gpusat::treeType::elements, gpusat::bagType::exponent, gpusat::treeType::maxId, gpusat::treeType::minId, gpusat::treeType::numSolutions, program, queue, and gpusat::treeType::size.
Referenced by solveJoin().
combineTree()
void gpusat::Solver::combineTree (treeType & to, treeType & from, cl_long numVars) protected
Parameters
to
from
numVars
References context, gpusat::treeType::elements, gpusat::treeType::maxId, gpusat::treeType::minId, gpusat::treeType::numSolutions, program, queue, and gpusat::treeType::size.
Referenced by solveIntroduceForget(), and solveJoin().
solveIntroduceForget()
void gpusat::Solver::solveIntroduceForget (satformulaType & formula, bagType & pnode, bagType & node, bagType & cnode, bool leaf, nodeType nextNode) protected
function to solve an introduce forget node
Parameters
formula the sat formula
pnode the parent of the current node
node the current node
cnode the child of the current node
leaf indicates that the current node is a leaf node
References gpusat::ARRAY, gpusat::bagType::bags, gpusat::satformulaType::clauses, combineTree(), gpusat::compVars(), context, gpusat::bagType::correction, gpusat::treeType::elements, gpusat::bagType::exponent, gpusat::bagType::id, gpusat::INTRODUCEFORGET, isSat, gpusat::JOIN, maxBag, gpusat::treeType::maxId, maxMemoryBuffer, gpusat::bagType::maxSize, maxTableSize, memorySize, gpusat::treeType::minId, numIntroduceForget, gpusat::treeType::numSolutions, gpusat::satformulaType::numWeights, gpusat::printbagType(), program, queue, gpusat::treeType::size, gpusat::bagType::solution, solutionType, gpusat::TREE, gpusat::bagType::variables, gpusat::satformulaType::variableWeights, and verbose.
Referenced by solveProblem().
solveJoin()
void gpusat::Solver::solveJoin (bagType & node, bagType & edge1, bagType & edge2, satformulaType & formula, nodeType nextNode) protected
function to solve a join node
Parameters
node the node to save the solutions in
edge1 the first child node
edge2 the second child node
formula the sat formula
References gpusat::ARRAY, gpusat::bagType::bags, cleanTree(), combineTree(), context, gpusat::bagType::correction, gpusat::treeType::elements, gpusat::bagType::exponent, gpusat::INTRODUCEFORGET, isSat, gpusat::JOIN, maxBag, gpusat::treeType::maxId, maxMemoryBuffer, gpusat::bagType::maxSize, maxTableSize, memorySize, gpusat::treeType::minId, numJoin, gpusat::treeType::numSolutions, gpusat::satformulaType::numWeights, program, queue, gpusat::treeType::size, gpusat::bagType::solution, solutionType, gpusat::TREE, gpusat::bagType::variables, and gpusat::satformulaType::variableWeights.
Referenced by solveProblem().
solveProblem()
void gpusat::Solver::solveProblem (treedecType & decomp, satformulaType & formula, bagType & node, bagType & pnode, nodeType lastNode)
Solves the sat formula with a given decomposition.
function to solve the sat problem
Parameters
decomp the tree decomposition
formula the sat formula
node the node to start from in the tree decompostion
Parameters
decomp The decomposition of the
formula The formula.
node The node.
pnode The pnode.
lastNode The last node.
References gpusat::bagType::bags, gpusat::bagType::edges, gpusat::treeType::elements, gpusat::Graphoutput::graphEdgeSet(), graphoutput, gpusat::bagType::id, gpusat::INTRODUCEFORGET, gpusat::Graphoutput::isEnabled(), isSat, gpusat::JOIN, gpusat::treeType::maxId, gpusat::bagType::maxSize, gpusat::treeType::minId, gpusat::Graphoutput::nodeBag(), gpusat::Graphoutput::nodeJoin(), gpusat::treeType::numSolutions, gpusat::printbagType(), gpusat::treeType::size, gpusat::solJson(), gpusat::bagType::solution, gpusat::solutiontable(), solutionType, solveIntroduceForget(), solveJoin(), gpusat::Visualization::tdTimelineAppend(), gpusat::bagType::variables, verbose, and visualization.
Member Data Documentation
context
cl::Context& gpusat::Solver::context protected
Referenced by cleanTree(), combineTree(), solveIntroduceForget(), and solveJoin().
graphoutput
Graphoutput* gpusat::Solver::graphoutput
Referenced by solveProblem().
isSat
cl_long gpusat::Solver::isSat = 1
Referenced by solveIntroduceForget(), solveJoin(), and solveProblem().
maxBag
cl_long gpusat::Solver::maxBag = 0
Referenced by solveIntroduceForget(), and solveJoin().
maxMemoryBuffer
cl_long gpusat::Solver::maxMemoryBuffer = 0
Referenced by solveIntroduceForget(), and solveJoin().
maxTableSize
cl_long gpusat::Solver::maxTableSize = 0
Referenced by main(), solveIntroduceForget(), and solveJoin().
memorySize
cl_long gpusat::Solver::memorySize protected
Referenced by solveIntroduceForget(), and solveJoin().
numIntroduceForget
cl_long gpusat::Solver::numIntroduceForget = 0
Referenced by main(), and solveIntroduceForget().
numJoin
cl_long gpusat::Solver::numJoin = 0
Referenced by main(), and solveJoin().
program
cl::Program& gpusat::Solver::program protected
Referenced by cleanTree(), combineTree(), solveIntroduceForget(), and solveJoin().
queue
cl::CommandQueue& gpusat::Solver::queue protected
Referenced by cleanTree(), combineTree(), solveIntroduceForget(), and solveJoin().
solutionType
dataStructure gpusat::Solver::solutionType = dataStructure::TREE
Referenced by solveIntroduceForget(), solveJoin(), and solveProblem().
verbose
bool gpusat::Solver::verbose = false
Referenced by solveIntroduceForget(), and solveProblem().
visualization
Visualization* gpusat::Solver::visualization
Referenced by solveProblem().
The documentation for this class was generated from the following files:
include/solver.h
src/solver.cpp