GPUSAT: gpusat::CutSetWidthFitnessFunction Class Reference
gpusat::CutSetWidthFitnessFunction Class Reference
#include <CutSetWidthFitnessFunction.h>
Public Member Functions
CutSetWidthFitnessFunction ()=default
~CutSetWidthFitnessFunction ()=default
CutSetWidthFitnessFunction * clone (void) const override
htd::FitnessEvaluation * fitness (const htd::IMultiHypergraph &graph, const htd::ITreeDecomposition &decomposition) const override
double getMaxCutSetSize (const htd::ITreeDecomposition &decomposition) const
Detailed Description
Fitness function that first minimizes the cut set size and then the width.
Constructor & Destructor Documentation
CutSetWidthFitnessFunction()
gpusat::CutSetWidthFitnessFunction::CutSetWidthFitnessFunction () default
Referenced by clone().
~CutSetWidthFitnessFunction()
gpusat::CutSetWidthFitnessFunction::~CutSetWidthFitnessFunction () default
Member Function Documentation
clone()
CutSetWidthFitnessFunction * gpusat::CutSetWidthFitnessFunction::clone (void) const override
References CutSetWidthFitnessFunction().
fitness()
htd::FitnessEvaluation * gpusat::CutSetWidthFitnessFunction::fitness (const htd::IMultiHypergraph & graph, const htd::ITreeDecomposition & decomposition) const override
References getMaxCutSetSize().
getMaxCutSetSize()
double gpusat::CutSetWidthFitnessFunction::getMaxCutSetSize (const htd::ITreeDecomposition & decomposition) const
Referenced by fitness().
The documentation for this class was generated from the following files:
include/FitnessFunctions/CutSetWidthFitnessFunction.h
src/FitnessFunctions/CutSetWidthFitnessFunction.cpp