GPUSAT: gpusat::WidthCutSetFitnessFunction Class Reference
gpusat::WidthCutSetFitnessFunction Class Reference
#include <WidthCutSetFitnessFunction.h>
Public Member Functions
WidthCutSetFitnessFunction ()=default
~WidthCutSetFitnessFunction ()=default
WidthCutSetFitnessFunction * clone (void) const override
htd::FitnessEvaluation * fitness (const htd::IMultiHypergraph &graph, const htd::ITreeDecomposition &decomposition) const override
double getMaxCutSetSize (const htd::ITreeDecomposition &decomposition) const
Detailed Description
Fitness function that first minimizes the width and then the cut set size.
Constructor & Destructor Documentation
WidthCutSetFitnessFunction()
gpusat::WidthCutSetFitnessFunction::WidthCutSetFitnessFunction () default
Referenced by clone().
~WidthCutSetFitnessFunction()
gpusat::WidthCutSetFitnessFunction::~WidthCutSetFitnessFunction () default
Member Function Documentation
clone()
WidthCutSetFitnessFunction * gpusat::WidthCutSetFitnessFunction::clone (void) const override
References WidthCutSetFitnessFunction().
fitness()
htd::FitnessEvaluation * gpusat::WidthCutSetFitnessFunction::fitness (const htd::IMultiHypergraph & graph, const htd::ITreeDecomposition & decomposition) const override
References getMaxCutSetSize().
getMaxCutSetSize()
double gpusat::WidthCutSetFitnessFunction::getMaxCutSetSize (const htd::ITreeDecomposition & decomposition) const
Referenced by fitness().
The documentation for this class was generated from the following files:
include/FitnessFunctions/WidthCutSetFitnessFunction.h
src/FitnessFunctions/WidthCutSetFitnessFunction.cpp