GPUSAT: gpusat Namespace Reference
gpusat Namespace Reference
Classes
class BagMatrix
struct bagType
type for a bag in the tree decomposition
class CNFParser
class CutSetWidthFitnessFunction
class Decomposer
class Graphoutput
class JoinSizeFitnessFunction
class NumJoinFitnessFunction
class Preprocessor
struct satformulaType
type for saving the sat formula
class Solver
struct TableLines
class TDParser
struct treedecType
type for saving a tree decomposition
struct treeType
tree type for storing the models
class Visualization
class WidthCutSetFitnessFunction
Enumerations
enum dataStructure { dataStructure::ARRAY, dataStructure::TREE }
enum nodeType { nodeType::JOIN, nodeType::INTRODUCEFORGET }
Functions
bool compTreedType (const bagType *a, const bagType *b)
bool compVars (const cl_long &a, const cl_long &b)
cl_double getCount (cl_long id, cl_long *tree, cl_long numVars)
long long int getTime ()
std::ostream & operator<< (std::ostream &os, const dataStructure ds)
std::ostream & operator<< (std::ostream &os, const std::vector< bagType * > vec)
std::ostream & operator<< (std::ostream &os, const std::vector< cl_long > vec)
void printbagType (bagType *bag, std::ostream &stream, int depth=0)
print information for a bag in the tree decomposition
void printtreedecType (treedecType *dec, std::ostream &stream)
print a tree decomposition
void printtreeType (treeType *tree, std::ostream &stream, size_t size, int depth=0)
TableLines solJson (bagType node, dataStructure solutionType)
std::string solutiontable (bagType node, dataStructure solutionType)
Generate a formatted stringoutput for a solved node with solutions.
Enumeration Type Documentation
dataStructure
enum gpusat::dataStructure strong
Enumerator
ARRAY
TREE
nodeType
enum gpusat::nodeType strong
Enumerator
JOIN
INTRODUCEFORGET
Function Documentation
compTreedType()
bool gpusat::compTreedType (const bagType * a, const bagType * b) inline
Function that compares two tree decompostions by id.
Parameters
a the first tree decompostion
b the second tree decomposition
Returns
a < b
References gpusat::bagType::id.
Referenced by gpusat::TDParser::parseTreeDecomp(), and gpusat::Preprocessor::preprocessDecomp().
compVars()
bool gpusat::compVars (const cl_long & a, const cl_long & b) inline
Function that compares two variables.
Parameters
a the first variable
b the second variable
Returns
true if abs a < b
Referenced by gpusat::Preprocessor::preprocessFacts(), and gpusat::Solver::solveIntroduceForget().
getCount()
cl_double gpusat::getCount (cl_long id, cl_long * tree, cl_long numVars) inline
returns the model count which corresponds to the given id
Parameters
id the id for which the model count should be returned
tree a pointer to the tree structure
numVars the number of variables in the bag
Returns
the model count
Referenced by main(), printtreeType(), solJson(), and solutiontable().
getTime()
long long int gpusat::getTime () inline
Returns
the time in millisecons since the epoch
Referenced by main().
operator<<() [1/3]
std::ostream& gpusat::operator<< (std::ostream & os, const dataStructure ds) inline
References ARRAY, and TREE.
operator<<() [2/3]
std::ostream& gpusat::operator<< (std::ostream & os, const std::vector< bagType * > vec) inline
operator<<() [3/3]
std::ostream& gpusat::operator<< (std::ostream & os, const std::vector< cl_long > vec) inline
printbagType()
void gpusat::printbagType (bagType * bag, std::ostream & stream, int depth = 0) inline
print information for a bag in the tree decomposition
References gpusat::bagType::bags, gpusat::bagType::correction, gpusat::bagType::edges, gpusat::bagType::exponent, gpusat::bagType::id, and gpusat::bagType::variables.
Referenced by gpusat::Solver::solveIntroduceForget(), and gpusat::Solver::solveProblem().
printtreedecType()
void gpusat::printtreedecType (treedecType * dec, std::ostream & stream) inline
print a tree decomposition
References gpusat::treedecType::bags, and gpusat::treedecType::numb.
Referenced by main().
printtreeType()
void gpusat::printtreeType (treeType * tree, std::ostream & stream, size_t size, int depth = 0) inline
References gpusat::treeType::elements, getCount(), gpusat::treeType::maxId, gpusat::treeType::minId, gpusat::treeType::numSolutions, and gpusat::treeType::size.
solJson()
TableLines gpusat::solJson (bagType node, dataStructure solutionType)
Construct Tablelines from a solved node of the tree decomposition If no solution is stored in this node return empty grid and totalSol -1.
References gpusat::BagMatrix::columns(), gpusat::bagType::correction, gpusat::treeType::elements, getCount(), gpusat::TableLines::headline, gpusat::treeType::minId, gpusat::bagType::solution, gpusat::TableLines::solutions, gpusat::TableLines::totalSol, TREE, and gpusat::bagType::variables.
Referenced by gpusat::Solver::solveProblem().
solutiontable()
std::string gpusat::solutiontable (bagType node, dataStructure solutionType) inline
Generate a formatted stringoutput for a solved node with solutions.
References gpusat::bagType::correction, gpusat::treeType::elements, getCount(), gpusat::treeType::minId, gpusat::bagType::solution, TREE, and gpusat::bagType::variables.
Referenced by gpusat::Solver::solveProblem().